### PR TITLE
fixed aboslute path

### PR DESCRIPTION
**Pull request by nivong**

### CODE REVIEW

**Comment by buluba89** [comment]
what is the problem that is being solved here ?

**Comment by nivong** [comment]
When you use a docker image it fails to get the path since I do not have direct root access in the Synology docker gui

**Comment by buluba89** [comment]
I dont have a synology so i dont know how it works. 
But i modified the docker image so you can pass arguments.
For example you can use
``
docker run -v /local/path/to/config.json:/path/in/container/config.json  buluba89/yatcobot  --config=/path/in/container/config.json
``

Did that help ?

**Comment by buluba89** [comment]
The cli.py is not intended to be called directly, instead there is the yatcobot.py in the root of the project that you should run like an ordinary linux command. 
I prefer the relative approach because if the package is installed somewhere else (e.g. /usr/local/bin) you could run the bot from inside the folder that your config is stored, because relative files are found relative to the working dir(aka the folder that you where in when you run the command)
Having said that maybe it would be useful to check some other location for a config before checking the working dir for a config, for example /etc/yatcobot/config.json, ~/.config/yatcobot/config.json or something like that.

Would that be useful ?

**Comment by nivong** [comment]
I am not calling the cli.py directly. What this piece of code this is:
checks the directory where the current program is working (that is cli.py) if cli is stored in (for example):
/usr/root/scripts/twitbot/yatcobot/ (looks for config,json here)
Than it moves up 1 directory (parent directory)
/usr/root/scripts/twitbot/ (looks for config.json here and finds it since this is where you stored the config.json.sample)

**Comment by buluba89** [comment]
But opening absolute /path/to/repo/config.json and config.json from working dir /path/to/repo is the same thing.
Am i missing something here ?

**Comment by buluba89** [comment]
It is working all these years just fine, so i think you got something wrong with the paths (if your problem is with docker the cli.py path is /yatcobot/yatcobo/cli.py, maybe that confused you)

Anyway i am closing this one as i prefer relative path than absolute. If you have any problems just use the --config argument

**Pull request closed without merging**
